name: RELEASE
on:
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ðŸ§±
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: âž•
        run: npm ci

      - name: âœ…
        run: npm test

      - name: ðŸ’š
        run: npm run build

      - name: ðŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
